import type { Metadata} from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from './components/Header'
import { Footer } from './components/Footer'
import { RightMenu } from './components/RightMenu'




const inter = Inter({ subsets: ['latin'] })

//Сео
export const metadata: Metadata = {
  title: 'Travian World',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode; auth: React.ReactNode;
}) {
  return (
    <html lang="en">
       <body>
        <div className='flex min-h-screen flex-col'>
          <Header /> 
          <main className='flex flex-1 flex-row justify-between'>
            <div className='mx-[52px] my-[30px] w-full'>{children}</div>
            <RightMenu />
          </main>
          <Footer />
        </div>
      </body>
    </html>
  
  );
}
